export const ruveltJobsAbi = [
  {
    type: 'function',
    name: 'completedJobCount',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: 'count', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalClaimableLiability',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'deliverWork',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'jobId', type: 'uint256' },
      { name: 'workRef', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'acceptJob',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'jobId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'finalizeJob',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'jobId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelJob',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'jobId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'withdraw',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'recipient', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimable',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: 'amount', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getSelectedContributors',
    stateMutability: 'view',
    inputs: [{ name: 'jobId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'allocationOf',
    stateMutability: 'view',
    inputs: [
      { name: 'jobId', type: 'uint256' },
      { name: 'contributor', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'workReferenceOf',
    stateMutability: 'view',
    inputs: [
      { name: 'jobId', type: 'uint256' },
      { name: 'contributor', type: 'address' },
    ],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'selectContributors',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'jobId', type: 'uint256' },
      { name: 'contributors', type: 'address[]' },
      { name: 'amounts', type: 'uint256[]' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'nextJobId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'event',
    name: 'ApplicationSubmitted',
    inputs: [
      { name: 'jobId', type: 'uint256', indexed: true },
      { name: 'applicant', type: 'address', indexed: true },
      { name: 'proposalRef', type: 'string', indexed: false },
    ],
  },
  {
    type: 'function',
    name: 'getJob',
    stateMutability: 'view',
    inputs: [{ name: 'jobId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'creator', type: 'address' },
          { name: 'budget', type: 'uint256' },
          { name: 'applicationDeadline', type: 'uint64' },
          { name: 'deliveryDeadline', type: 'uint64' },
          { name: 'reviewPeriod', type: 'uint64' },
          { name: 'reviewDeadline', type: 'uint64' },
          { name: 'deliveredCount', type: 'uint32' },
          { name: 'state', type: 'uint8' },
          { name: 'detailsRef', type: 'string' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getApplication',
    stateMutability: 'view',
    inputs: [
      { name: 'jobId', type: 'uint256' },
      { name: 'applicant', type: 'address' },
    ],
    outputs: [
      { name: 'exists', type: 'bool' },
      { name: 'proposalRef', type: 'string' },
    ],
  },
  {
    type: 'function',
    name: 'submitApplication',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'jobId', type: 'uint256' },
      { name: 'proposalRef', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'updateApplication',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'jobId', type: 'uint256' },
      { name: 'proposalRef', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'createJob',
    stateMutability: 'payable',
    inputs: [
      { name: 'detailsRef', type: 'string' },
      { name: 'budget', type: 'uint256' },
      { name: 'applicationDeadline', type: 'uint64' },
      { name: 'deliveryDeadline', type: 'uint64' },
      { name: 'reviewPeriod', type: 'uint64' },
    ],
    outputs: [{ name: 'jobId', type: 'uint256' }],
  },
  {
    type: 'event',
    name: 'JobCreated',
    inputs: [
      { name: 'jobId', type: 'uint256', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'budget', type: 'uint256', indexed: false },
      { name: 'applicationDeadline', type: 'uint64', indexed: false },
      { name: 'deliveryDeadline', type: 'uint64', indexed: false },
      { name: 'detailsRef', type: 'string', indexed: false },
    ],
  },
] as const;
